version: '3'

networks:
  mqtt:

services:
  nodered:
    depends_on:
      - mosquitto
    build:
      context: nodered
      dockerfile: Dockerfile
    networks:
      - mqtt
    ports:
      - 1880:1880

  mosquitto:
    image: eclipse-mosquitto
    command: ["mosquitto", "-c", "/mosquitto-no-auth.conf"]
    networks:
      - mqtt

  deye-mqtt:
    image: ghcr.io/kbialek/deye-inverter-mqtt
    env_file:
      - config.env
    networks:
      - mqtt


